spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.0.0.101:3306/skean0
    username: skean
    password: skean
  output:
    ansi.enabled: ALWAYS

server:
  port: 8980
herd:
  localThumbnailRepoPath: D:/tmp/herdThumbs